### PR TITLE
Kill dead code

### PR DESCRIPTION
**Pull request by mqp**
Just getting rid of more and more dead code paths that we don't want. Lilliput wasn't being used anymore, and is now gone. Since we moved off of the Reticulum-generated URLs, we don't need to use the feature where putting a ".png" and ".jpg" at the end of the URL tell it what format to output extracted PDF pages in anymore (it will just always make a PNG since that's the best we know) so that's gone.

Next step: change the URL space for requests to be something we endorse.

### CODE REVIEW

**Comment by gfodor** [comment]
I fully intend to use farspark's image resizing features for the scene
browser, and eventually the landing page for photos, etc. Can we put this
back in?

**Comment by mqp** [comment]
Sure, with a few caveats:

- If you have an image resizing use case that is like "process uploaded images to serve on the website", should that be implemented right alongside "proxy and transform arbitrary URLs for the VR client"? As you can see, it isn't going to share much code, and it also doesn't seem in line with your idea about separating concerns onto different boxes. (For example, if hypothetically all of Farspark were a separate Elixir app running on separate EC2 instances the way we discussed earlier, it doesn't make sense to me that we would colocate the scene thumbnailing code into that Elixir app instead of the one hosting the website.) I would rather write code in Reticulum to do that resizing at scene upload time.

- If we do want to implement it in Farspark and make calls to Farspark to do the resizing, I don't want to put it back in the same way it just was, because that way didn't make sense (e.g. it ran Lilliput every time on images from the disk cache, the resize and PDF transform surprisingly inhabit the same code path, it implemented random format-changing options as well as resizing, etc.) Would we even want it to take an image URL as input, or take the input image as a POST body?

So if you want to do this then let's talk for 15 minutes about how you want the scene upload process and browser to work and implement some code that does it the way it should be.

**Comment by gfodor** [comment]
Sure. at 30k feet I'd prefer this not be in elixir because of the BEAM crash risk of calling out to native libraries to do the resizing. ofc the origins of farspark were imgproxy, so fast resizing/cropping/conversion  was the core functionality of it that i didn't have to write myself :)

in general the pattern that imgproxy has is the one I'd like to have as well: a GET request specifies the origin URL for an image and at request time does the transformation and returns the new image. this is then put behind CDN with proper cache headers. the PDF case in farspark I wrote myself and it was not part of imgproxy, and the reason for the additional local caching layers was to avoid additional overhead on the cache miss case for a new page or simultaneous fetches for the same page across different CDN edge nodes -- this wasn't a big deal for the basic image case but since there is a lot of overhead (and a synchronous lock) for the PDF case I decided to fill in the missing caching layers.

**Comment by gfodor** [comment]
the main use case for imgproxy is the one that we haven't had up until this point -- you have a bunch of uploaded raw images sitting at URLs and you want to draw them onto a webpage in smaller or cropped sizes in a way that isn't slow or poorly cached -- with imgproxy you just rewrite the URLs in the HTML to point to your proxy/CDN and you are done. (vs the usual alternative where you have a magic set of sizes you support and convert them all in an insane batch job at upload time, if you even can do it.)

**Comment by mqp** [comment]
Hmm, OK, I don't really like the sound of the imgproxy approach as opposed to the batch-job-at-upload-time approach (the only benefit seems like enabling on-demand new formats and sizes at image serving time, and the penalties are having to operate a separate service and rely on a caching layer outside of it.) Is there some particular reason it's appealing to you?

(As usual, this is in the category where I would not even consider doing anything but the simplest possible approach, since it seems to me that we are drowning in complexity and don't have anywhere near enough manpower to do all of the work we have put on our plates. The traditional approach sounds like twenty lines of code that shells out to Imagemagick and uploads images to S3. The non-traditional approach entails having a service with thousands of lines of code that I spend days debugging.)

> Sure. at 30k feet I'd prefer this not be in elixir because of the BEAM crash risk of calling out to native libraries to do the resizing. ofc the origins of farspark were imgproxy, so fast resizing/cropping/conversion was the core functionality of it that i didn't have to write myself :)

I see. It sounds like this is another thing that we wish was in Elixir-but-separate-OTP-app, similar to the rest of the Farspark functionality.

In order of preference, I suggest:

- Shelling out to imagemagick in Reticulum and uploading images to S3. This sounds straightforward, low-risk, and does not require me to spend days doing work items like "understand the behavior and concurrency characteristics of the Go HTTP server so that our environment load times don't take 20 seconds when someone hits our scene browser with stuff that isn't in cache" and "figure out how to write a Habitat plan that builds runs a local Go package", so you can see why I might like it.
- Putting this functionality back into Farspark with an imgproxy-style contract, but nicer. This is easy to do, but a bad result.
- Putting this functionality into a new Elixir service, with the intent of later repeating this trick to make Elixir services out of the other Farspark functionality that we don't want in the same Erlang process as our Phoenix app, as described yesterday. If I understood stuff about Elixir, I guess this would be a matter of hours, but unfortunately I am not so it would take a bunch of work that I'm not prepared to invest right now.

If we end up on number 2, I still want to understand what functionality we need (e.g. do we want format conversions, or just resizing?) so let's still talk about it tomorrow before I implement it.

**Comment by gfodor** [comment]
the batch job at upload time approach results in a ton of complexity as soon as you need to resize all of your images because of a bug or a new image format target, or as soon as you want to be sure that the resize jobs actually complete successfully and don't fail 0.01% of the time resulting in permanently broken images. the farspark code is way simpler, and is just dumb HTTP request/response with caching. (this is why discord for example has migrated to this strategy, hence lilliput.)

**Comment by gfodor** [comment]
for example to stand up the system you propose in a rails stack or php stack you'd add gearman or sidekiq and a queue like rabbitmq or redis. otherwise you won't have a way to batch and resize all your images or be sure that if a resize fails (which it will) it will be retried properly

**Comment by gfodor** [comment]
i'm also not sure of the aversion to the code deleted here for this problem, lilliput is being run in production at scale, so presumably the operation risk here is the stuff outside of that? like, before this code was deleted i considered this problem basically solved for us and not something I'd ever have to worry about ever.

**Comment by mqp** [comment]
Well, this is starting to get dangerously close to "arguing about the thing in your head which I don't know anything about yet", but the thing I think I would suggest would be to do it synchronously on scene upload, and rely on the client to receive an error and retry if something about scene upload fails. I think we can get away with this since the volume of scene uploads is not going to be very large, even if Hubs is very popular.

**Comment by gfodor** [comment]
what's the reason we can just put this code in, start using it the way i intended to, and then revisit it if it turns into a mess? these seem like invented problems. i don't understand the underlying motivation for deleting this code. it's incidentally dead because I haven't gotten to the UI tasks that need it yet, but the service it provided is something I want to use.

**Comment by gfodor** [comment]
here's an example of a job processing library for elixir:

https://github.com/akira/exq

you need to architect this problem in this way if you are not resizing the images on demand since you'll inevitably need to generate images for the entire set of source images. so it's necessary complexity unless you solve the problem in the way we were going to with farspark

**Comment by mqp** [comment]
> like, before this code was deleted i considered this problem basically solved for us and not something I'd ever have to worry about ever.

I just don't agree with that consideration. This PR happened because Farspark is *not even close* to done or working as well as we want. For example, it is literally broken right now for a reason we don't understand yet. It hangs mysteriously frequently when you make a request to it, for reasons we don't understand. Obviously we expect to add features to it in the future, as described yesterday.

This PR is because this thing which is not working very well is also, coincidentally or not, full of code that wasn't being exercised, wasn't well-tested, and was in the middle of the same code path that our client relies on when you load it. This is not a reasonable state of affairs. The way I know how to fix problems like this is to try to simplify them down to the essentials so that I can get a grip on what is going on, and then rebuild parts of it that make sense.

**Comment by gfodor** [comment]
OK I'll probably wave the white flag at this point until I'm completely blocked on this problem :) I feel like deleting all this code from the repo is not really the correct methodology for diagnosing the throughput issue you're running into -- I'd just set up a load test shim to repro the problem and find the bottleneck.  Like you said there's not a lot of code in farspark, and the code you deleted is largely code that's already battle hardened from discord.

**Comment by mqp** [comment]
Note that the existing collective "solution" represented by Farspark and its client code before I started working on the media pipeline completely broke Jim's environment workflow, resulted in literally dozens of extra round trips and other lag (e.g. extra work in Farspark) every time you loaded an environment or spawned an object in the client, caused the client to wait a second every time you clicked the arrow on a PDF before any visual feedback was produced, etc. etc. My approach works. I will continue my approach until the most serious of the problems I described above are fixed, at least unless you come and do it your way first.

These things aren't coincidences that you can fix independently by testing individual things and writing extra branches in the program. They are direct consequences of optimizing software for things that aren't "being a simple system that everyone can easily understand and work with."

**Comment by mqp** [comment]
> OK I'll probably wave the white flag at this point until I'm completely blocked on this problem

I'm still more or less happy to just put this functionality back in Farspark -- I just want to sync up on what the scene upload subsystem is like so that I understand which functionality to put (which input and output formats we care about, etc.) and I'll do it by making a new API endpoint that does this instead of conflating it with the VR client asset transformation code.

**Comment by gfodor** [comment]
I really don't like arguing over GitHub issues :) Fine to disagree on this for now, I'm not blocked, but we'll need to find a good solution to this problem soon. The two immediate use-cases:

- Properly crop and resize the screenshot image from Spoke for Slack unfurl image (referenced in the meta tag)

- Same, but for the scene tile list

Soon thereafter, we're likely going to have a variety of formats and sizes we want to crop, filter, and scale and potentially compose in-game camera photos for:

- Photo landing page

- Social media sharing (potentially watermarked)

- Use profile page

- Convert camera videos to animated GIFs

**Comment by gfodor** [comment]
some requirements:

- If we need a new image size, or need to change the cropping, or want to apply a new filter, or whatever, it needs to be possible to do so in a way that will affect all previously uploaded images

- We need to have decent guarantees that if there are failures during resize, it won't cause a perma-busted img tag

Some other additional things:

- Ideally don't shell out or use NIF from BEAM
- User shouldn't have to wait for image processing to complete to get response from API
- No new data stores
- Outages, load, or backlog on image resizing should not affect reticulum API response error rate or latency

(note the CDN-proxied GET approach, or a full on queued job system are the only approaches I know that meets all of these -- and queue one requires a new data store. there are probably erlangy ones.)

**Pull request merged**
